import type { Metadata } from "next";

import "./globals.css";
import { Mulish, Fredoka } from "next/font/google"

const fredoka = Fredoka({
  subsets: ['latin'],
  variable: "--font-fredoka",
  preload: true
})

const mulish = Mulish({
  subsets: ['latin'],
  variable: "--font-mulish",
  preload: true
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type TRootLayout = Readonly<{ children: React.ReactNode }>

export default function RootLayout({ children }: TRootLayout) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${fredoka.variable} ${mulish.variable}`}>
        {children}
      </body>
    </html>
  );
}
