import type { Metadata } from "next";
import "./globals.css";
import { Mulish, Fredoka, Inter } from "next/font/google"
import { Toaster } from "sonner";
import AuthSessionProvider from "#/providers/AuthSessionProvider";
import QueryProvider from "#/providers/QueryProvider";

const fredoka = Fredoka({
  subsets: ['latin'],
  variable: "--font-fredoka",
  preload: true
})

const mulish = Mulish({
  subsets: ['latin'],
  variable: "--font-mulish",
  preload: true
})

const inter = Inter({
  subsets: ['latin'],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-inter",
  preload: true
})


export const metadata: Metadata = {
  title: "Chinesewithmeggie",
  description: "Generated by create next app",
};

type TRootLayout = Readonly<{ children: React.ReactNode }>

export default function RootLayout({ children }: TRootLayout) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${fredoka.variable} ${mulish.variable} ${inter.variable}`}>
        <AuthSessionProvider>
          <QueryProvider>
            {children}
          </QueryProvider>
        </AuthSessionProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
